name: Publish SSCEP

on: [push, pull_request]

jobs:
  build:
    name: Building SSCEP
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build sscep-builder image
      uses: docker/build-push-action@v3
      with:
        context: .
        tags: sscep-builder
        target: sscep-builder

    - name: Build sscep-dist image
      uses: docker/build-push-action@v3
      with:
        context: .
        tags: sscep-dist
        target: sscep-dist
        outputs: type=docker,dest=sscep-dist.tar

    - name: Store sscep-dist image
      uses: actions/cache@v3
      with:
        key: sscep-dist-${{ github.sha }}
        path: sscep-dist.tar

  publish:
    name: Publishing SSCEP
    if: github.event_name == 'push' && github.ref_name == 'v0.10.0-pki'
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Retrieve sscep-dist image
      uses: actions/cache@v3
      with:
        key: sscep-dist-${{ github.sha }}
        path: sscep-dist.tar

    - name: Publish sscep-dist image
      run: |
        docker load --input sscep-dist.tar
        docker tag sscep-dist ghcr.io/${{ github.repository_owner }}/sscep-dist:latest
        docker push ghcr.io/${{ github.repository_owner }}/sscep-dist:latest
